### ISSUE TITLE
a simple synthetic example with `single_snp_select` fails

### ISSUE THREAD

**Issue by DSLituiev** [MicrosoftGenomics/FaST-LMM#11]
Hi, I am trying to feed my data into  `single_snp_select`  and getting various errors. Here is one demonstration with synthetic data:

```
N = 100
p = 20

from pysnptools.snpreader import SnpData

def snp_from_pandas(df):
    indiv_ids = zip(df.index.tolist(), ["."] * len(df.index))
    snp_ids = [("_".join(["%s"% y for y in x]) if type(x) in (tuple, list) \
                          else "%s"% x) for x in df.columns.tolist()]
    out = SnpData(indiv_ids, snp_ids, df.as_matrix())
    return out

rnad =  snp_from_pandas( 
    pd.DataFrame(np.random.randn(N), index = ["ind%u" % n for n in range(N)]) 
    )

snpd =  snp_from_pandas( 
    pd.DataFrame(np.random.randint(0,2, size=(N, p)), 
                 index = ["ind%u" % n for n in range(N)],
                 columns = ["snp%u" % n for n in range(p)],
                ).astype(float) 
    )

single_snp_select(snpd, pheno=rnad,  k_list = [2,8,16], n_folds = 3 )
```

First I was getting error that genotypes must be floats (which is counter intuitive a bit), and now I get:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-189-458a40b5d93a> in <module>()
----> 1 single_snp_select(snpd, pheno=rnad,  k_list = [2,8,16], n_folds = 3 )

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp_select.pyc in single_snp_select(test_snps, pheno, G, covar, k_list, n_folds, just_return_selected_snps, seed, output_file_name, GB_goal, force_full_rank, force_low_rank, h2, runner)
    180                                 input_files = common_input_files,
    181                                 name = "k_index_to_nLL",
--> 182                                 runner=runner)
    183     best_k = k_list_in[np.argmin(k_index_to_nLL)]
    184 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)
    178         runner = Local()
    179 
--> 180     result = runner.run(dist)
    181     return result
    182 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/Local.pyc in run(self, distributable)
     25     def run(self, distributable):
     26         JustCheckExists().input(distributable)
---> 27         result = run_all_in_memory(distributable)
     28         JustCheckExists().output(distributable)
     29         return result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in run_all_in_memory(work)
     39         work_sequence = work.work_sequence()
     40         result_sequence = work_sequence_to_result_sequence(work_sequence)
---> 41         return work.reduce(result_sequence)
     42 
     43 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in reduce(self, output_seq)
     79         '''
     80 
---> 81         return self.reducer(output_seq)
     82 
     83 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in work_sequence_to_result_sequence(work_sequence)
     23     for work in work_sequence:
     24         if callable(work):
---> 25             result = work()
     26         else:
     27             result = run_all_in_memory(work)

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in <lambda>(i, input_arg)
     67                 logging.debug("executing %i" % i)
     68                 with _dyn_vars(is_in_nested=False):
---> 69                     yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg)  # the 'i=i',etc is need to get around a strangeness in Python
     70             else:
     71                 assert self.nested is not None, "real assert"

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in dowork(self, i, input_arg)
     94         logging.debug("executing {0}".format(input_arg))
     95         work = lambda : self.mapper(input_arg)
---> 96         result = run_all_in_memory(work)
     97         return result
     98 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in run_all_in_memory(work)
     34     '''
     35     if callable(work):
---> 36         return work()
     37     else:
     38         assert hasattr(work,"work_sequence"), "Your work item doesn't have a work_sequence. This can be caused by having 'map_reduce(nested=something,...)' where you should have 'map_reduce(mapper=something,...)' because the 'something' is not a nested 'map_reduce'"

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in <lambda>()
     93         #logging.info("{0}, {1}".format(len(train_snp_idx), len(test_snp_idx)))
     94         logging.debug("executing {0}".format(input_arg))
---> 95         work = lambda : self.mapper(input_arg)
     96         result = run_all_in_memory(work)
     97         return result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp_select.pyc in k_index_to_nLL_mapper(k)
    164             fastlmm.fit(K0_train=G_train, X=covar_in[train_idx,:], y=pheno_in[train_idx,:], h2=h2) #iid intersection means when can give the whole covariate and pheno
    165             G_test = G_in[test_idx,sid_idx_in_fold] if k > 0 else KernelIdentity(G_in.iid,G_in.iid[test_idx]) #!!! instead of this, which blows up when # of iids is large, should switch to linear regression model with k is 0
--> 166             nll,mse = fastlmm.score(K0_whole_test=G_test,X=covar_in[test_idx,:],y=pheno_in[test_idx,:],return_mse_too=True) #iid intersection means when can give the whole covariate and pheno
    167             nll_sum += nll
    168             mse_sum += mse

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/inference/fastlmm_predictor.pyc in score(self, X, y, K0_whole_test, K1_whole_test, iid_if_none, return_mse_too)
    432         :rtype: a float of the negative log likelihood and, optionally, a float of the mean squared error.
    433         """
--> 434         mean0, covar0 = self.predict(K0_whole_test=K0_whole_test,K1_whole_test=K1_whole_test,X=X,iid_if_none=iid_if_none)
    435         y = _pheno_fixup(y, iid_if_none=covar0.iid)
    436         mean, covar, y = intersect_apply([mean0, covar0, y])

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/inference/fastlmm_predictor.pyc in predict(self, X, K0_whole_test, K1_whole_test, iid_if_none)
    512             varg = self.h2 * self.sigma2
    513             vare = (1.-self.h2) * self.sigma2
--> 514             Ainv = LA.inv((1./vare) * np.dot(self.G.T,self.G) + (1./varg)*np.eye(self.G.shape[1]))
    515             testAinv = np.dot(Gstar.test.val, Ainv)
    516             pheno_predicted = np.dot(X.val,self.beta) + (1./vare) * np.dot(np.dot(testAinv,self.G.T),self.y-np.dot(self.X,self.beta))

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/linalg/basic.pyc in inv(a, overwrite_a, check_finite)
    656 
    657     """
--> 658     a1 = _asarray_validated(a, check_finite=check_finite)
    659     if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:
    660         raise ValueError('expected square matrix')

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/_lib/_util.pyc in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    185             raise ValueError('masked arrays are not supported')
    186     toarray = np.asarray_chkfinite if check_finite else np.asarray
--> 187     a = toarray(a)
    188     if not objects_ok:
    189         if a.dtype is np.dtype('O'):

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/function_base.pyc in asarray_chkfinite(a, dtype, order)
   1020     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
   1021         raise ValueError(
-> 1022             "array must not contain infs or NaNs")
   1023     return a
   1024 

ValueError: array must not contain infs or NaNs
```

System:
MacOSX 10.10.5
Python2.7, 
Fast-LMM: Latest commit `5dfd12f`

**Comment by DSLituiev** [comment]
When running on my own small data set (N = 92, p=751), I get:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-197-458a40b5d93a> in <module>()
----> 1 single_snp_select(snpd, pheno=rnad,  k_list = [2,8,16], n_folds = 3 )

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp_select.pyc in single_snp_select(test_snps, pheno, G, covar, k_list, n_folds, just_return_selected_snps, seed, output_file_name, GB_goal, force_full_rank, force_low_rank, h2, runner)
    194                                 covar=covar, leave_out_one_chrom=True,
    195                                 GB_goal=GB_goal,  force_full_rank=force_full_rank, force_low_rank=force_low_rank, h2=h2,
--> 196                                 output_file_name=output_file_name,runner=runner)
    197 
    198     return single_snp_result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in single_snp(test_snps, pheno, K0, K1, mixing, covar, covar_by_chrom, leave_out_one_chrom, output_file_name, h2, log_delta, cache_file, GB_goal, interact_with_snp, force_full_rank, force_low_rank, G0, G1, runner)
    205                    output_files = [output_file_name],
    206                    name = "single_snp (leave_out_one_chrom), out='{0}'".format(output_file_name),
--> 207                    runner = runner)
    208 
    209     return frame

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)
    178         runner = Local()
    179 
--> 180     result = runner.run(dist)
    181     return result
    182 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/Local.pyc in run(self, distributable)
     25     def run(self, distributable):
     26         JustCheckExists().input(distributable)
---> 27         result = run_all_in_memory(distributable)
     28         JustCheckExists().output(distributable)
     29         return result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in run_all_in_memory(work)
     39         work_sequence = work.work_sequence()
     40         result_sequence = work_sequence_to_result_sequence(work_sequence)
---> 41         return work.reduce(result_sequence)
     42 
     43 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in reduce(self, output_seq)
     79         '''
     80 
---> 81         return self.reducer(output_seq)
     82 
     83 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in reducer_closure(frame_sequence)
    187 
    188         def reducer_closure(frame_sequence):
--> 189             frame = pd.concat(frame_sequence)
    190             frame.sort_values(by="PValue", inplace=True)
    191             frame.index = np.arange(len(frame))

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tools/merge.pyc in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
    843                        keys=keys, levels=levels, names=names,
    844                        verify_integrity=verify_integrity,
--> 845                        copy=copy)
    846     return op.get_result()
    847 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tools/merge.pyc in __init__(self, objs, axis, join, join_axes, keys, levels, names, ignore_index, verify_integrity, copy)
    873             objs = [objs[k] for k in keys]
    874         else:
--> 875             objs = list(objs)
    876 
    877         if len(objs) == 0:

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in work_sequence_to_result_sequence(work_sequence)
     23     for work in work_sequence:
     24         if callable(work):
---> 25             result = work()
     26         else:
     27             result = run_all_in_memory(work)

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in <lambda>(i, input_arg)
     67                 logging.debug("executing %i" % i)
     68                 with _dyn_vars(is_in_nested=False):
---> 69                     yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg)  # the 'i=i',etc is need to get around a strangeness in Python
     70             else:
     71                 assert self.nested is not None, "real assert"

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in dowork(self, i, input_arg)
     94         logging.debug("executing {0}".format(input_arg))
     95         work = lambda : self.mapper(input_arg)
---> 96         result = run_all_in_memory(work)
     97         return result
     98 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in run_all_in_memory(work)
     34     '''
     35     if callable(work):
---> 36         return work()
     37     else:
     38         assert hasattr(work,"work_sequence"), "Your work item doesn't have a work_sequence. This can be caused by having 'map_reduce(nested=something,...)' where you should have 'map_reduce(mapper=something,...)' because the 'something' is not a nested 'map_reduce'"

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in <lambda>()
     93         #logging.info("{0}, {1}".format(len(train_snp_idx), len(test_snp_idx)))
     94         logging.debug("executing {0}".format(input_arg))
---> 95         work = lambda : self.mapper(input_arg)
     96         result = run_all_in_memory(work)
     97         return result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in nested_closure(chrom)
    182                                         force_full_rank=force_full_rank,force_low_rank=force_low_rank,
    183                                         output_file_name=None, block_size=block_size, interact_with_snp=interact_with_snp,
--> 184                                         runner=Local())
    185 
    186             return distributable

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in _internal_single(K0, test_snps, pheno, covar, K1, mixing, h2, log_delta, cache_file, force_full_rank, force_low_rank, output_file_name, block_size, interact_with_snp, runner)
    632                        input_files=[test_snps],output_files=[output_file_name],
    633                        name="single_snp(output_file={0})".format(output_file_name),
--> 634                        runner=runner)
    635     return frame
    636 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)
    178         runner = Local()
    179 
--> 180     result = runner.run(dist)
    181     return result
    182 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/Local.pyc in run(self, distributable)
     25     def run(self, distributable):
     26         JustCheckExists().input(distributable)
---> 27         result = run_all_in_memory(distributable)
     28         JustCheckExists().output(distributable)
     29         return result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in run_all_in_memory(work)
     39         work_sequence = work.work_sequence()
     40         result_sequence = work_sequence_to_result_sequence(work_sequence)
---> 41         return work.reduce(result_sequence)
     42 
     43 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in reduce(self, output_seq)
     79         '''
     80 
---> 81         return self.reducer(output_seq)
     82 
     83 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in reducer_closure(result_sequence)
    619             create_directory_if_necessary(output_file_name)
    620 
--> 621         frame = pd.concat(result_sequence)
    622         frame.sort_values(by="PValue", inplace=True)
    623         frame.index = np.arange(len(frame))

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tools/merge.pyc in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
    843                        keys=keys, levels=levels, names=names,
    844                        verify_integrity=verify_integrity,
--> 845                        copy=copy)
    846     return op.get_result()
    847 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tools/merge.pyc in __init__(self, objs, axis, join, join_axes, keys, levels, names, ignore_index, verify_integrity, copy)
    876 
    877         if len(objs) == 0:
--> 878             raise ValueError('No objects to concatenate')
    879 
    880         if keys is None:

ValueError: No objects to concatenate
```

**Comment by CarlKCarlK** [comment]
Dmytro,


Thanks for using FaST-LMM and thanks for your note.


I’ve enclosed below sample code that fixes the problem. My additions are marked with “#cmk”. The key is that every SNP must have a chromosome number so that FaST-LMM can do leave-out-one-chrom learning.


[Also, I’ve added a note to my copy of code. A future version will give a better error message if the chromosome number is not set but is needed.]


Thanks again,

Carl





#cmk: Turn on logging just for entertainment  value

import logging

logging.basicConfig(level=logging.INFO)

 

N = 100 

p = 20

 

from pysnptools.snpreader import SnpData

import pandas as pd

import numpy as np

 

#cmk: Set random seed to make debugging deterministic

np.random.seed(0)

 

from fastlmm.association import single_snp_select

 

def snp_from_pandas(df):

    indiv_ids = zip(df.index.tolist(), ["."] * len(df.index))

    snp_ids = [("_".join(["%s"% y for y in x]) if type(x) in (tuple, list) \

                          else "%s"% x) for x in df.columns.tolist()]

    #cmk: Add chromosome number to each SNP (alternating 1 and 2) to support leave_out_one_chrom learning

    pos = [[i%2+1,0,0] for i in xrange(len(df.columns))]

    out = SnpData(indiv_ids, snp_ids, df.as_matrix(), pos=pos)

    return out

 

rnad =  snp_from_pandas( 

    pd.DataFrame(np.random.randn(N), index = ["ind%u" % n for n in range(N)]) 

    )

 

snpd =  snp_from_pandas( 

    pd.DataFrame(np.random.randint(0,2, size=(N, p)), 

                 index = ["ind%u" % n for n in range(N)],

                 columns = ["snp%u" % n for n in range(p)],

                ) .astype(float) 

    )

 

single_snp_select(snpd, pheno=rnad,  k_list = [2,8,16], n_folds = 3 )


 






From: Dmytro Lituiev
Sent: ‎Friday‎, ‎June‎ ‎3‎, ‎2016 ‎2‎:‎17‎ ‎PM
To: MicrosoftGenomics/FaST-LMM





When running on my own small data set (N = 92, p=751), I get:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-197-458a40b5d93a> in <module>()
----> 1 single_snp_select(snpd, pheno=rnad,  k_list = [2,8,16], n_folds = 3 )

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp_select.pyc in single_snp_select(test_snps, pheno, G, covar, k_list, n_folds, just_return_selected_snps, seed, output_file_name, GB_goal, force_full_rank, force_low_rank, h2, runner)
    194                                 covar=covar, leave_out_one_chrom=True,
    195                                 GB_goal=GB_goal,  force_full_rank=force_full_rank, force_low_rank=force_low_rank, h2=h2,
--> 196                                 output_file_name=output_file_name,runner=runner)
    197 
    198     return single_snp_result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in single_snp(test_snps, pheno, K0, K1, mixing, covar, covar_by_chrom, leave_out_one_chrom, output_file_name, h2, log_delta, cache_file, GB_goal, interact_with_snp, force_full_rank, force_low_rank, G0, G1, runner)
    205                    output_files = [output_file_name],
    206                    name = "single_snp (leave_out_one_chrom), out='{0}'".format(output_file_name),
--> 207                    runner = runner)
    208 
    209     return frame

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)
    178         runner = Local()
    179 
--> 180     result = runner.run(dist)
    181     return result
    182 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/Local.pyc in run(self, distributable)
     25     def run(self, distributable):
     26         JustCheckExists().input(distributable)
---> 27         result = run_all_in_memory(distributable)
     28         JustCheckExists().output(distributable)
     29         return result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in run_all_in_memory(work)
     39         work_sequence = work.work_sequence()
     40         result_sequence = work_sequence_to_result_sequence(work_sequence)
---> 41         return work.reduce(result_sequence)
     42 
     43 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in reduce(self, output_seq)
     79         '''
     80 
---> 81         return self.reducer(output_seq)
     82 
     83 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in reducer_closure(frame_sequence)
    187 
    188         def reducer_closure(frame_sequence):
--> 189             frame = pd.concat(frame_sequence)
    190             frame.sort_values(by="PValue", inplace=True)
    191             frame.index = np.arange(len(frame))

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tools/merge.pyc in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
    843                        keys=keys, levels=levels, names=names,
    844                        verify_integrity=verify_integrity,
--> 845                        copy=copy)
    846     return op.get_result()
    847 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tools/merge.pyc in __init__(self, objs, axis, join, join_axes, keys, levels, names, ignore_index, verify_integrity, copy)
    873             objs = [objs[k] for k in keys]
    874         else:
--> 875             objs = list(objs)
    876 
    877         if len(objs) == 0:

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in work_sequence_to_result_sequence(work_sequence)
     23     for work in work_sequence:
     24         if callable(work):
---> 25             result = work()
     26         else:
     27             result = run_all_in_memory(work)

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in <lambda>(i, input_arg)
     67                 logging.debug("executing %i" % i)
     68                 with _dyn_vars(is_in_nested=False):
---> 69                     yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg)  # the 'i=i',etc is need to get around a strangeness in Python
     70             else:
     71                 assert self.nested is not None, "real assert"

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in dowork(self, i, input_arg)
     94         logging.debug("executing {0}".format(input_arg))
     95         work = lambda : self.mapper(input_arg)
---> 96         result = run_all_in_memory(work)
     97         return result
     98 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in run_all_in_memory(work)
     34     '''
     35     if callable(work):
---> 36         return work()
     37     else:
     38         assert hasattr(work,"work_sequence"), "Your work item doesn't have a work_sequence. This can be caused by having 'map_reduce(nested=something,...)' where you should have 'map_reduce(mapper=something,...)' because the 'something' is not a nested 'map_reduce'"

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in <lambda>()
     93         #logging.info("{0}, {1}".format(len(train_snp_idx), len(test_snp_idx)))
     94         logging.debug("executing {0}".format(input_arg))
---> 95         work = lambda : self.mapper(input_arg)
     96         result = run_all_in_memory(work)
     97         return result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in nested_closure(chrom)
    182                                         force_full_rank=force_full_rank,force_low_rank=force_low_rank,
    183                                         output_file_name=None, block_size=block_size, interact_with_snp=interact_with_snp,
--> 184                                         runner=Local())
    185 
    186             return distributable

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in _internal_single(K0, test_snps, pheno, covar, K1, mixing, h2, log_delta, cache_file, force_full_rank, force_low_rank, output_file_name, block_size, interact_with_snp, runner)
    632                        input_files=[test_snps],output_files=[output_file_name],
    633                        name="single_snp(output_file={0})".format(output_file_name),
--> 634                        runner=runner)
    635     return frame
    636 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in map_reduce(input_seq, mapper, reducer, input_files, output_files, name, runner, nested)
    178         runner = Local()
    179 
--> 180     result = runner.run(dist)
    181     return result
    182 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/Local.pyc in run(self, distributable)
     25     def run(self, distributable):
     26         JustCheckExists().input(distributable)
---> 27         result = run_all_in_memory(distributable)
     28         JustCheckExists().output(distributable)
     29         return result

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/runner/__init__.pyc in run_all_in_memory(work)
     39         work_sequence = work.work_sequence()
     40         result_sequence = work_sequence_to_result_sequence(work_sequence)
---> 41         return work.reduce(result_sequence)
     42 
     43 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/util/mapreduce.pyc in reduce(self, output_seq)
     79         '''
     80 
---> 81         return self.reducer(output_seq)
     82 
     83 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fastlmm/association/single_snp.pyc in reducer_closure(result_sequence)
    619             create_directory_if_necessary(output_file_name)
    620 
--> 621         frame = pd.concat(result_sequence)
    622         frame.sort_values(by="PValue", inplace=True)
    623         frame.index = np.arange(len(frame))

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tools/merge.pyc in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
    843                        keys=keys, levels=levels, names=names,
    844                        verify_integrity=verify_integrity,
--> 845                        copy=copy)
    846     return op.get_result()
    847 

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tools/merge.pyc in __init__(self, objs, axis, join, join_axes, keys, levels, names, ignore_index, verify_integrity, copy)
    876 
    877         if len(objs) == 0:
--> 878             raise ValueError('No objects to concatenate')
    879 
    880         if keys is None:

ValueError: No objects to concatenate

**Comment by DSLituiev** [comment]
Thank you! this makes sense.
