### ISSUE TITLE
single_snp_all_plus_select() without 'leave_out_one_chrom'?

### ISSUE THREAD

**Issue by cizydorczyk** [MicrosoftGenomics/FaST-LMM#25]
Hello,

I am wondering if it is currently possible to run the "single_snp_all_plus_select()" function, but have it not depend on 'leave_out_one_chrom'? I ask because I have some interest in running FaST-LMM, and would like to use the "all plus select" function, using a dataset with a single chromosome.

Unfortunately, it seems as though this is not currently possible. According to the API documentation for 'single_snp_all_plus_select', "All work is done via ‘leave_out_one_chrom’, that one chromosome is tested and the kernels are constructed from the other chromosomes."

I am also wondering whether there is any plan to implement such a version, or whether there would generally be too few use cases.

Thank you,
Conrad Izydorczyk

**Comment by CarlKCarlK** [comment]
Dear Conrad & my FaST-LMM Collaborators,

Looking at the code, removing the leave-one-out from single_snp_all_plus_select would be difficult (because there are loops within loops within looks).

But are you sure you would want to? My understanding is that it would just end up selecting SNPs near the SNP of interest and would not produce meaningful results.

I have one idea that is not really a suggestion (because it may be a bad idea): Put in fake chromosome numbers for the SNPs. Then the program will run. If near SNPs are (mostly) given the same chrom number they will not selected. (If your data is in BED format, you could edit the text BIM file to change chrom numbers. Alternatively, if your data is small enough to load into memory, you could use PySnpData to create a SnpData object with the same SNP values, but with different chrom information).
(Collaborators, please chime in on the wisdom of this idea.)


  *   Carl


________________________________

**Comment by heckerma** [comment]
Thats a quick way that should get the code to run.  A more involved approach that should yield better results is to create multiple pairs of snps.  In each pair you have (1) a contiguous range of snps (say 10% of genome), and (2) all other snps except those close to (ie, in high ld with) 1.  Label these as chr 1 and 2, and run the code.  Keep only the results for chr 1.   Now repeat this process so as to process all snps.

Sent from my iPhone

On Jan 9, 2018, at 11:18 AM, Carl Kadie <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Conrad & my FaST-LMM Collaborators,

Looking at the code, removing the leave-one-out from single_snp_all_plus_select would be difficult (because there are loops within loops within looks).

But are you sure you would want to? My understanding is that it would just end up selecting SNPs near the SNP of interest and would not produce meaningful results.

I have one idea that is not really a suggestion (because it may be a bad idea): Put in fake chromosome numbers for the SNPs. Then the program will run. If near SNPs are (mostly) given the same chrom number they will not selected. (If your data is in BED format, you could edit the text BIM file to change chrom numbers. Alternatively, if your data is small enough to load into memory, you could use PySnpData to create a SnpData object with the same SNP values, but with different chrom information).
(Collaborators, please chime in on the wisdom of this idea.)


* Carl


________________________________

**Comment by cizydorczyk** [comment]
Thank you for your responses - I will look into each of these methods.

The reason I ask is because I have been playing with the idea of running FaST-LMM using a microbial SNP data set using a species (Pseudomonas aeruginosa) that has only a single chromosome. Perhaps it is somewhat simplistic of me, but I do not see why the improvements in power and controlling type I error when using two GSMs would not translate to a microbial data set as well. Given that microbial GWAS methods seem to be following in the footsteps of human GWAS, I figured it was worth a shot!

Best,
Conrad Izydorczyk

**Comment by heckerma** [comment]
Hi Conrad,

Definitely worth a try!  It’ll be a bit of a pain, but it should work.

Best, David
