### ISSUE TITLE
std=.0.000000 has illegal value for SNPs[:][0]

### ISSUE THREAD

**Issue by mb3152** [MicrosoftGenomics/FaST-LMM#38]
When I run: results_df = single_snp(bed_fn,  pheno, count_A1=True)

I get a lot of these messages:

std=.0.000000 has illegal value for SNPs[:][0]
NaN beta value seen, may be due to an SNC (a constant SNP)

What am I doing wrong? 

Thanks!

**Comment by CarlKCarlK** [comment]
This can usually be ignored. It means that in the data being read, for some of your "SNPs" only one nucleotide value is being seen. (In other words, it is a SNC, single nucleotide *constant*, rather than a SNP.) The algorithms generally don't care, although of course if *every* SNP was really a SNC there would be no way to do a GWAS.
