### ISSUE TITLE
"fastlmm.util.SamplePi Failed" when running with test.py

### ISSUE THREAD

**Issue by YuhuiWang1** [MicrosoftGenomics/FaST-LMM#40]
Hi,
I successfully installed the fastlmm in Mac. But I encounter the following errors when I attempt to run $python test.py.
Could you guide me to fix it?
Thank you!
Yuhui

INFO:root:normalized Means: [-709.49691217 -709.53567265 -709.56406106 -709.60471265 -709.64031636
 -709.67318162 -709.7083669  -709.74267763 -709.77528574 -709.80745401
 -709.84184521]
INFO:root:best num PCs: 0
INFO:root:computing svd...
INFO:root:done after 0.7890 seconds
INFO:root:Projecting individuals to PCs space...
.**********************************************************************
**File "/Library/Python/2.7/site-packages/fastlmm/util/SamplePi.py", line 25, in fastlmm.util.SamplePi
Failed example:**
    round(runner.run(distributable),2)
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest fastlmm.util.SamplePi[5]>", line 1, in <module>
        round(runner.run(distributable),2)
      File "/Library/Python/2.7/site-packages/fastlmm/util/runner/LocalMultiProc.py", line 46, in run
        util.create_directory_if_necessary(run_dir_rel, isfile=False)
      File "/Library/Python/2.7/site-packages/fastlmm/util/util.py", line 320, in create_directory_if_necessary
        raise Exception("not valid path: '{0}'. (Working directory is '{1}'".format(directory_name,os.getcwd()))
    Exception: not valid path: 'runs/2019-03-11_20_19_24_335494029633'. (Working directory is '/Library/Python/2.7/site-packages/fastlmm/util'
/Library/Python/2.7/site-packages/fastlmm/util/util.py:332: UserWarning: creating directory robust=True, try#0,time=11 error: not valid path: '/Library/Python/2.7/site-packages/fastlmm/util/pi_work'. (Working directory is '/Library/Python/2.7/site-packages/fastlmm/util'
  warnings.warn("creating directory robust=True, try#{0},time={3} error: not valid path: '{1}'. (Working directory is '{2}'".format(i, directory_name,os.getcwd(),int(time_to_sleep)))
/Library/Python/2.7/site-packages/fastlmm/util/util.py:332: UserWarning: creating directory robust=True, try#1,time=12 error: not valid path: '/Library/Python/2.7/site-packages/fastlmm/util/pi_work'. (Working directory is '/Library/Python/2.7/site-packages/fastlmm/util'
  warnings.warn("creating directory robust=True, try#{0},time={3} error: not valid path: '{1}'. (Working directory is '{2}'".format(i, directory_name,os.getcwd(),int(time_to_sleep)))

**Comment by CarlKCarlK** [comment]
Yuhua Wang,

Thanks for using FastLMM. Sorry about the problem you’re seeing and thank you for finding it.

I believe the problem is related to the test program trying to create a temporary directory under the directory where FastLMM is install. This is allowed on some OS, but (apparently) not on MAC OS. When I can, I fix this by moving the temp directory to a better place.

In the meantime, you can work around the problem by

  *   Trying to run the test with as a super user (Linux) or admin (Windows). I don’t know what the equivalent on Mac is.
  *   Or, just ignoring the problem (because it seems to be a bug in the testing code, not in FastLMM itself.

Thanks again for using FastLMM.

Yours,
Carl

________________________________
